plugins {
    id 'java'
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.runelite.net' }
}

def runeLiteVersion = project.findProperty('runeliteVersion') ?: 'latest.release'

dependencies {
    compileOnly "net.runelite:client:${runeLiteVersion}"
    testImplementation "net.runelite:client:${runeLiteVersion}"
    testImplementation "net.runelite:jshell:${runeLiteVersion}"
}

group = 'com.farmingdiscordstatus'
version = '0.1.0'

java {
    toolchain { languageVersion = JavaLanguageVersion.of(11) }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.fork = true
}
